{"data":{"node":null},"errors":[{"type":"NOT_FOUND","path":["node"],"locations":[{"line":1,"column":3}],"message":"Could not resolve to a node with the global id of 'PVT_kwHOCnxPXs4ArUQB'."}]}
